- hosts: all
  tasks:
    - name: stop container
      shell:  docker container stop app-container                    #name of container 
    - name: remove container
      shell: docker container rm app-container
    - name: remove docker image
      shell: docker image rm chinthala2000/app-mon-devops:mahesh                      #name of images (docker images)
    - name: create new container
      shell: docker container run -itd --name app-container -p 9000:80 chinthala2000/app-mon-devops:mahesh